# Generated by Django 3.0.7 on 2020-06-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Hushen300Component',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('index_code', models.TextField(blank=True, null=True)),
        #         ('con_code', models.TextField(blank=True, null=True)),
        #         ('trade_date', models.TextField(blank=True, null=True)),
        #         ('weight', models.FloatField(blank=True, null=True)),
        #     ],
        #     options={
        #         'db_table': 'Hushen300component',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='LatestFactor',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('ts_code', models.TextField(blank=True, null=True)),
        #         ('trade_date', models.TextField(blank=True, null=True)),
        #         ('adj_factor', models.FloatField(blank=True, null=True)),
        #     ],
        #     options={
        #         'db_table': 'latest_factor',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Marketinfo',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('ts_code', models.CharField(max_length=64)),
        #         ('trade_date', models.DateField()),
        #         ('open', models.FloatField(blank=True, null=True)),
        #         ('high', models.FloatField(blank=True, null=True)),
        #         ('low', models.FloatField(blank=True, null=True)),
        #         ('close', models.FloatField(blank=True, null=True)),
        #         ('vol', models.FloatField(blank=True, null=True)),
        #         ('pct_chg', models.FloatField(blank=True, null=True)),
        #         ('adj_factor', models.FloatField(blank=True, null=True)),
        #     ],
        #     options={
        #         'db_table': 'marketinfo',
        #         'managed': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='TradeCal',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('exchange', models.CharField(blank=True, max_length=64, null=True)),
        #         ('trade_date', models.DateField(blank=True, null=True)),
        #         ('is_open', models.BooleanField(blank=True, null=True)),
        #     ],
        #     options={
        #         'db_table': 'trade_cal',
        #         'managed': False,
        #     },
        # ),
        migrations.CreateModel(
            name='BackwardMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.TextField(blank=True, null=True)),
                ('trade_date', models.DateField(db_index=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('pct_chg', models.FloatField(blank=True, null=True)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Book',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('book_name', models.CharField(max_length=64)),
        #         ('add_time', models.DateTimeField(auto_now_add=True)),
        #     ],
        # ),
        migrations.CreateModel(
            name='CurrentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.TextField(blank=True, null=True)),
                ('ts_code', models.TextField(blank=True, null=True)),
                ('position', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('wavg_cost', models.FloatField(blank=True, null=True)),
                ('return_field', models.FloatField(blank=True, db_column='return', null=True)),
                ('pct_return', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForwardMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.TextField(blank=True, null=True)),
                ('trade_date', models.DateField(db_index=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('pct_chg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.TextField()),
                ('ts_code', models.TextField()),
                ('trade_date', models.DateField()),
                ('position', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('wavg_cost', models.FloatField(blank=True, null=True)),
                ('return_field', models.FloatField(blank=True, db_column='return', null=True)),
                ('pct_return', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marketnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.TextField(blank=True, null=True)),
                ('trade_date', models.DateField(db_index=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('vol', models.FloatField(blank=True, null=True)),
                ('pct_chg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.TextField()),
                ('trade_date', models.DateField()),
                ('ts_code', models.TextField()),
                ('order_type', models.TextField()),
                ('limit_price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('amount_type', models.TextField()),
                ('validity_term', models.IntegerField(blank=True, null=True)),
                ('order_status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True)),
            ],
        ),
    ]
