# Generated by Django 3.0.7 on 2020-06-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysisTool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradecalendar',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='tradecalendar',
            name='is_open',
        ),
    ]
